# Generated by Django 2.0.2 on 2018-02-09 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brief',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('fx', 'Forex'), ('bn', 'Binary'), ('ico', 'ICO'), ('cm', 'Cloud Mining'), ('og', 'Online Games'), ('o', 'Other')], max_length=4)),
                ('experience', models.CharField(choices=[('ls_1', 'Up to 1 year'), ('ls_3', 'From 1 to 3 years'), ('mr_3', 'More than 3 years'), ('n_ex', 'I want to found a startup and I don’t have experience')], max_length=4)),
                ('aim', models.CharField(choices=[('new', 'Create a new turn-key project from scratch '), ('mk', 'Create a general marketing strategy for my project'), ('pt', 'Connect the optimal payment system for my project'), ('ld', 'Increase the number of leads for my project'), ('brd', 'Strengthen brand by increasing audience coverage'), ('o', 'Other')], max_length=4)),
                ('stage', models.CharField(choices=[('bg', "I'm beginner and have no results yet"), ('prep', 'I passed the preparatory stage and I plan to start active attracting clients'), ('st', 'All necessary directions of my business are created and started'), ('imp', 'Everything works perfectly, but I want a point improvement of some processes'), ('o', 'Other')], max_length=4)),
                ('strategies', models.CharField(choices=[('stg', 'The development strategy is strong and was adjusted a minimum number of times'), ('no_s', 'I have no strategy, I act through the way of trial and error'), ('cs', 'The main activity is considered to the detail but at some points I don’t have the right planning'), ('sit', 'In my opinion, my approach is situational. It is extremely difficult to build a long-term strategy of actions'), ('o', 'Other')], max_length=4)),
                ('audience', models.CharField(choices=[('sm_c', 'Small group in one of the countries'), ('lg_c', 'Broad coverage in one country'), ('sm_i', 'Limited audience in several countries'), ('lg_i', 'Large audience in several countries'), ('o', 'Other')], max_length=4)),
                ('callcenter', models.CharField(choices=[('own', 'I have/plan to create my own call center'), ('ots', 'I use / plan to use outsourced call center'), ('msg', 'I replace the call center with messaging or chatting'), ('rb', 'The process of communication with customers is robotized'), ('no_c', 'I don’t see the need to create a call center'), ('o', 'Other')], max_length=4)),
                ('marketing', models.CharField(choices=[('own', 'Yes, we develop/plan to develop all the necessary creatives ourselves'), ('fr', 'No, we order advertisement at advertising agencies or freelancers'), ('co', 'We plan our activity for a long-term and order all advertising support on a contract basis, following the brand-book and the general strategy'), ('o', 'Other')], max_length=4)),
                ('payment', models.CharField(choices=[('cd', 'Bank cards'), ('tsf', 'Bank Transfer'), ('wl', 'E-Wallet'), ('cr', 'Cryptocurrency'), ('o', 'Other')], max_length=4)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'brief',
                'verbose_name_plural': 'briefs',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('comment', models.CharField(blank=True, max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='brief',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='leads.Lead'),
        ),
    ]
