# Generated by Django 2.0.2 on 2018-02-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20180220_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='leads.Lead', to_field='email'),
        ),
    ]
