# Generated by Django 2.0.2 on 2018-03-05 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20180228_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('message', models.CharField(blank=True, max_length=1000)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'lead',
                'verbose_name_plural': 'leads',
            },
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'lead', 'verbose_name_plural': 'leads'},
        ),
        migrations.AddField(
            model_name='message',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='leads.Lead', to_field='email'),
        ),
    ]
